console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
enable_cursor_positioning = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    leading_powerline_symbol = "\uE0B6"
    background = 'blue'
    foreground = 'black'
    template = " 󰣇 <b>{{ .UserName }}@{{ .HostName }}</b> "

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = "\uE0BC"
    background = 'cyan'
    foreground = 'black'
    template = '  <b>{{ .Path }}</b> '

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = "\uE0BC"
    background = 'green'
    foreground = 'black'
    template = ' <b>{{ .HEAD }}</b> '

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    powerline_symbol = "\uE0BC"
    background = 'transparent'
    foreground = 'green'
    template = "\uE0BB"

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    powerline_symbol = "\uE0BC"
    background = 'transparent'
    foreground = 'green'
    template = "\uE0BB"

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    leading_diamond = "\uE0BA"
    trailing_diamond = "\uE0B4"
    background = 'green'
    foreground = 'black'
    template = ' in <b>{{ .Shell }}</b> at <b>{{ .CurrentDate | date .Format }}</b> '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{ if gt .Code 0 }}red{{ end }}",
      "{{ if eq .Code 0 }}blue{{ end }}",
    ]
    template = "\u276f"

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{ if gt .Code 0 }}red{{ end }}",
      "{{ if eq .Code 0 }}green{{ end }}",
    ]
    template = '{{ div .Ms 1000 }}s  '

    [blocks.segments.properties]
      threshold = 5000

[transient_prompt]
  background = 'transparent' 
  foreground_templates = [
    "{{ if gt .Code 0 }}red{{ end }}",
    "{{ if eq .Code 0 }}green{{ end }}",
  ]
  template = "\u276f "
